"""initial run metadata schema

Revision ID: 1427673e9a31
Revises:
Created: 2026-08-14 16:27:10.579709
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "1427673e9a31"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_version",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier", "version", name="uq_dataset_identifier_version"),
    )
    with op.batch_alter_table("dataset_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dataset_version_identifier"), ["identifier"], unique=False
        )

    op.create_table(
        "run_config",
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("resolved_config", sa.JSON(), nullable=False),
        sa.Column("overrides", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("config_hash"),
    )
    op.create_table(
        "run_set",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("axes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_set_id", sa.String(length=64), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("derived_from_run_id", sa.String(length=64), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=True),
        sa.Column("reproducible", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_hash"],
            ["run_config.config_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["derived_from_run_id"],
            ["run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_set_id"],
            ["run_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_config_hash"), ["config_hash"], unique=False)
        batch_op.create_index(
            "ix_run_config_hash_created", ["config_hash", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_run_run_set_id"), ["run_set_id"], unique=False)

    op.create_table(
        "job",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("backend", sa.String(length=64), nullable=False),
        sa.Column("work_dir", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_state"), ["state"], unique=False)

    op.create_table(
        "result_artifact",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "kind", name="uq_artifact_run_kind"),
    )
    with op.batch_alter_table("result_artifact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_result_artifact_run_id"), ["run_id"], unique=False)

    op.create_table(
        "run_dataset",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "dataset_id"),
    )
    op.create_table(
        "run_summary",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("termination", sa.String(length=32), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("final_so2_pptv", sa.Float(), nullable=True),
        sa.Column("peak_h2so4_pptv", sa.Float(), nullable=True),
        sa.Column("peak_number_cm3", sa.Float(), nullable=True),
        sa.Column("final_surface_area", sa.Float(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("run_summary", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_run_summary_termination"), ["termination"], unique=False
        )

    op.create_table(
        "job_transition",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_transition", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_transition_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_transition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_transition_job_id"))

    op.drop_table("job_transition")
    with op.batch_alter_table("run_summary", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_summary_termination"))

    op.drop_table("run_summary")
    op.drop_table("run_dataset")
    with op.batch_alter_table("result_artifact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_result_artifact_run_id"))

    op.drop_table("result_artifact")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_state"))
        batch_op.drop_index(batch_op.f("ix_job_run_id"))

    op.drop_table("job")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_run_set_id"))
        batch_op.drop_index("ix_run_config_hash_created")
        batch_op.drop_index(batch_op.f("ix_run_config_hash"))

    op.drop_table("run")
    op.drop_table("run_set")
    op.drop_table("run_config")
    with op.batch_alter_table("dataset_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_version_identifier"))

    op.drop_table("dataset_version")
    # ### end Alembic commands ###
