"""reproducible is a boolean

Revision ID: c0236fb572d2
Revises: 1427673e9a31
Created: 2026-08-14 17:16:21.643335
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "c0236fb572d2"
down_revision = "1427673e9a31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "reproducible", existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.alter_column(
            "reproducible", existing_type=sa.Boolean(), type_=sa.INTEGER(), existing_nullable=True
        )

    # ### end Alembic commands ###
